- name: vim | retrieve vimrc
  uri:
    url: https://raw.githubusercontent.com/amix/vimrc/master/vimrcs/basic.vim
    method: GET
    return_content: yes
  register: vim_vimrc_content
  tags: [ vim ]
- name: vim | place vimrc file
  ansible.builtin.copy:
    content: "{{ vim_vimrc_content.content }}"
    dest: "{{ ansible_env.HOME }}/.vimrc"
    mode: 0644
  tags: [ vim ]